src/Aldor/InftechBundle/Entity/Entry.php
<?php

namespace Aldor\InftechBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Entry
 */
class Entry
{
    /**
     * @var integer
     */
    protected $id;

    /**
     * @var \DateTime
     */
    protected $date;

    /**
     * @var \DateTime
     */
    protected $publicationDateStart;

    /**
     * @var string
     */
    protected $url;

    /**
     * @var string
     */
    protected $contentFormatter;

    /**
     * @var string
     */
    protected $content;

    /**
     * @var string
     */
    protected $rawContent;

    /**
     * @var string
     */
    protected $description;

    /**
     * @var string
     */
    protected $title;

    /**
     * @var string
     */
    protected $title_slug;

    /**
     * @var string
     */
    protected $keywords;

    /**
     * @var \DateTime
     */
    protected $modified;

    /**
     * @var integer
     */
    protected $comment_count = 0;

    /**
     * @var boolean
     */
    protected $public  = true;


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set date
     *
     * @param \DateTime $date
     * @return Entry
     */
    public function setDate($date)
    {
        $this->date = $date;

        return $this;
    }

    /**
     * Get date
     *
     * @return \DateTime
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Set publicationDateStart
     *
     * @param \DateTime $publicationDateStart
     * @return Entry
     */
    public function setPublicationDateStart($publicationDateStart)
    {
        $this->publicationDateStart = $publicationDateStart;

        return $this;
    }

    /**
     * Get publicationDateStart
     *
     * @return \DateTime
     */
    public function getPublicationDateStart()
    {
        return $this->publicationDateStart;
    }

    /**
     * Set url
     *
     * @param string $url
     * @return Entry
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set contentFormatter
     *
     * @param string $contentFormatter
     * @return Entry
     */
    public function setContentFormatter($contentFormatter)
    {
        $this->contentFormatter = $contentFormatter;

        return $this;
    }

    /**
     * Get contentFormatter
     *
     * @return string
     */
    public function getContentFormatter()
    {
        return $this->contentFormatter;
    }

    /**
     * Set content
     *
     * @param string $content
     * @return Entry
     */
    public function setContent($content)
    {
        $this->content = $content;

        return $this;
    }

    /**
     * Get content
     *
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Set rawContent
     *
     * @param string $rawContent
     * @return Entry
     */
    public function setRawContent($rawContent)
    {
        $this->rawContent = $rawContent;

        return $this;
    }

    /**
     * Get rawContent
     *
     * @return string
     */
    public function getRawContent()
    {
        return $this->rawContent;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return Entry
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    public function getRawDescription() {
        $description = $this->description;
        $description = html_entity_decode($description, ENT_QUOTES, 'utf-8');
        $description = preg_replace('/<.*?>/', '', $description);
        $description = str_replace("\xC2\xA0",' ',$description);
        return $description;
    }
    /**
     * Set title
     *
     * @param string $title
     * @return Entry
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set title_slug
     *
     * @param string $titleSlug
     * @return Entry
     */
    public function setTitleSlug($titleSlug)
    {
        $this->title_slug = $titleSlug;

        return $this;
    }

    /**
     * Get title_slug
     *
     * @return string
     */
    public function getTitleSlug()
    {
        return $this->title_slug;
    }

    /**
     * Set keywords
     *
     * @param string $keywords
     * @return Entry
     */
    public function setKeywords($keywords)
    {
        $this->keywords = $keywords;

        return $this;
    }

    /**
     * Get keywords
     *
     * @return string
     */
    public function getKeywords()
    {
        return $this->keywords;
    }

    /**
     * Set modified
     *
     * @param \DateTime $modified
     * @return Entry
     */
    public function setModified($modified)
    {
        $this->modified = $modified;

        return $this;
    }

    /**
     * Get modified
     *
     * @return \DateTime
     */
    public function getModified()
    {
        return $this->modified;
    }

    /**
     * Set comment_count
     *
     * @param integer $commentCount
     * @return Entry
     */
    public function setCommentCount($commentCount)
    {
        $this->comment_count = $commentCount;

        return $this;
    }

    /**
     * Get comment_count
     *
     * @return integer
     */
    public function getCommentCount()
    {
        return $this->comment_count;
    }

    /**
     * Set public
     *
     * @param boolean $public
     * @return Entry
     */
    public function setPublic($public)
    {
        $this->public = $public;

        return $this;
    }

    /**
     * Get public
     *
     * @return boolean
     */
    public function getPublic()
    {
        return $this->public;
    }
    /**
     * @ORM\PrePersist
     */
    public function preInsert()
    {
        // Add your code here
    }

    /**
     * @ORM\PreUpdate
     */
    public function preUpdate()
    {
        // Add your code here
    }

    /**
     * @ORM\PreRemove
     */
    public function preRemove()
    {
        // Add your code here
    }
    /**
     * @var string
     */
    private $full_photo_size = 'big';


    /**
     * Set full_photo_size
     *
     * @param string $fullPhotoSize
     * @return Entry
     */
    public function setFullPhotoSize($fullPhotoSize)
    {
        $this->full_photo_size = $fullPhotoSize;

        return $this;
    }

    /**
     * Get full_photo_size
     *
     * @return string
     */
    public function getFullPhotoSize()
    {
        return $this->full_photo_size;
    }

    public function getMedia()
    {
        throw "Not implemented";
    }
    public function getTags()
    {
        throw "Not implemented";
    }
    public function getCategory()
    {
        throw "Not implemented";
    }

}

src/Aldor/InftechBundle/Resources/views/Block/categories.html.twig
{% embed 'AldorInftechBundle::sidebar.html.twig'  %}
    {% block siedebar_title%}Kategorie{% endblock%}
    {%block siedebar_content %}
    <ul class="entries">
    {% for category in categories%}
        <li class="entry style-recent-list type-post">

        <a href="{{ path('blog_category', {'slug': category.slug }) }}" class="entry-title">
        <i class="fa fa-chevron-right"></i>
        {{ category.name }}
        </a>
        <li>
    {%endfor%}
    </ul>

    {% endblock%}
{% endembed %}

src/Aldor/InftechBundle/Resources/views/Block/footer_categories.html.twig
<div class="widget col-xs-6 col-sm-2">
<h4 class="widget-title">{{title}}</h4>

    <ul class="entries links links-2-cols">
    {% for category in categories%}
        <li>
        <a href="{{ path('blog_category', {'slug': category.slug }) }}" class="entry-title">
            {{ category.name }}</a>
        <li>
    {% endfor %}
    </ul>
</div>

src/Aldor/InftechBundle/Resources/views/Block/footer_gallerycategories.html.twig
<div class="widget">
<h4 class="widget-title">{{title}}</h4>

    <ul class="entries links links-2-cols">
    {% for category in categories%}
        <li>
        <a href="{{ path('gallery_photocategory', {'galleryslug': category.gallery.slug, 'photocategoryslug': category.slug }) }}">
            {{ category.name }}</a>
        </li>
    {% endfor %}
    </ul>
</div>

src/Aldor/InftechBundle/Resources/views/Block/footer_tags.html.twig
<div class="widget col-xs-6 col-sm-2">
<h4 class="widget-title">{{ title }}</h4>

    <ul class="entries links links-2-cols">
    {% for tag in tags%}
        <li>
        <a href="{{ path('blog_tag', {'slug': tag.name }) }}" class="entry-title">
        {{ tag.name }}
        </a>
        <li>
    {% endfor %}
    </ul>
  </div>

src/Aldor/InftechBundle/Resources/views/Block/recent.html.twig
<div class="item active">
<h2 class="section-title ribbon ribbon-focus"><a href="{{ path(routeName) }}"> {{ title}}</a></h2>

<div class="row entries">
    {% for entry in entiies %}
    <article class="entry style-grid type-post col-md-6 col-lg-3 colheight-sm-1">
        
        <header class="entry-header">
            <p class="small"><a href="blog.html">{{ entry.category }}</a></p>
            <h3 class="entry-title"><a href="single.html">{{ entry.title }}</a> </h3>
            <div class="entry-meta">
                <span class="entry-date"><a href="blog.html"><time datetime="{{entry.date|date(dateFormat)}}">{{ entry.date | time_ago_in_words(false, true) }}</time></a></span>
                <span class="entry-author"> by Aldor</span>
            </div>
        </header>
        
        <figure class="entry-thumbnail">

            <a href="single.html" class="overlay overlay-primary"></a>

            <!-- to disable lazy loading, remove data-src and data-src-retina -->
            <img src="../img/placeholder.gif" data-src="http://placehold.it/480x280" data-src-retina="http://placehold.it/720x420" width="480" height="280" alt="">

            <!--fallback for no javascript browsers-->
            <noscript>
                <img src="http://placehold.it/480x280" alt="">
            </noscript>

        </figure>

    </article>
    {% endfor %}

</div><!--/.row.entries-->

</div><!--/.item-->

src/Aldor/InftechBundle/Resources/views/Block/recent_photo.html.twig
<div class="item {% if active %}active {%endif%}">
<h2 class="section-title ribbon ribbon-focus"><a href="{{ path('gallery_show', {'slug': gallery.slug}) }}"> {{ title}}</a></h2>

<div class="row entries">
    {% for entry in entities %}
    <article class="entry style-grid type-post col-md-6 col-lg-3 colheight-sm-1">
        
        <header class="entry-header">
            <p class="small"><a href="{{ path('gallery_photocategory', {'galleryslug': entry.categories[0].gallery.slug, 'photocategoryslug': entry.categories[0].slug})}}">{{ entry.category }}</a></p>
            <h3 class="entry-title"><a href="{{ path('gallery_photocategory', {'galleryslug': entry.categories[0].gallery.slug, 'photocategoryslug': entry.categories[0].slug})}}">{{ entry.title }}</a> </h3>
            <div class="entry-meta">
                <span class="entry-date"><a href="{{ path('gallery_photocategory', {'galleryslug': entry.categories[0].gallery.slug, 'photocategoryslug': entry.categories[0].slug})}}"><time datetime="{{entry.date|date(dateFormat)}}">{{ entry.date | time_ago_in_words(false, true)|trans }}</time></a></span>
            </div>
        </header>
        
        <figure class="entry-thumbnail">

            <a href="{{ path('gallery_photocategory', {'galleryslug': entry.categories[0].gallery.slug, 'photocategoryslug': entry.categories[0].slug})}}" class="overlay overlay-primary"></a>

            {% set img_url = media_public_url(entry.image, imageSize)   %}
            {% include "AldorInftechBundle::image.html.twig" with {
                "img_url": img_url,
                "alt": entry.title,
                "width": "480",
                "height": "280"
            }
            %}

        </figure>

    </article>
    {% endfor %}

</div><!--/.row.entries-->

</div><!--/.item-->

src/Aldor/InftechBundle/Resources/views/Block/recent_posts.html.twig
    {% for post in posts %}
        {% if loop.index ==  1   %}
            <article class="entry style-grid style-hero hero-sm-largest type-post col-sm-12 col-md-8 col-lg-8 col-xl-6 colheight-sm-1 colheight-md-2 colheight-lg-2 colheight-xl-2">
        {% elseif loop.index == 2 %}
            <article class="entry style-grid style-hero type-post col-sm-6 col-md-4 col-lg-4 col-xl-6 colheight-sm-1 colheight-md-1 colheight-lg-1 colheight-xl-2">
        {% elseif loop.index == 3 %}
            <article class="entry style-grid style-hero hero-sm-larger hero-xl-normal type-post col-sm-6 col-md-4 col-lg-4 col-xl-4 colheight-sm-1 colheight-md-2 colheight-lg-2 colheight-xl-1 sm-pull-right">
        {% else %}
            <article class="entry style-grid style-hero type-post col-sm-6 col-md-4 colheight-md-1 colheight-sm-1 colheight-md-1 colheight-lg-1 colheight-lg-1 colheight-xl-1">
        {% endif %}
                <div class="ribbon ribbon-pulled ribbon-small ribbon-highlight">
                    <a href="{{ path('blog_category', {'slug': post.categoryslug}) }}">{{post.category.name }}</a>
                </div>
                <header class="entry-header">
                    <h3  class="entry-title">
                        <a href="{{ path('blog_post', {  'year': post.date | date('Y'), 'month': post.date | date('m'),  'title': post.titleslug}) }}">{{ post.title }}</a>
                    </h3>
                    <div class="entry-meta">
                        <h4>
                        {{post.rawdescription|slice(0, 75)}} {% if post.rawdescription|length > 75 %}...{% endif %}    
                        </h4>
                        <span class="entry-date"> <time datetime="{{ post.date | date(dateFormat) }} ">{{ post.date |time_ago_in_words(false, true)|trans }}</time></span>
                    </div>
                </header>
            <figure class="entry-thumbnail">
                    {% if loop.index < 3 %}
                        {% set img_url = media_public_url(post.media, imagesSize[0])   %}
                        {% set width = "680" %}
                        {% set height = "452" %}
                    {% else %}
                        {% set img_url = media_public_url(post.media, imagesSize[1])   %}
                        {% set width = "480" %}
                        {% set height = "280" %}
                    {% endif %}
                    <a href="{{ path('blog_post', {  'year': post.date | date('Y'), 'month': post.date | date('m'),  'title': post.titleslug}) }}" class="overlay overlay-primary">
                            </a>
                         {% include "AldorInftechBundle::image.html.twig" with {
                            "img_url": img_url,
                            "alt": post.title,
                            "width": width,
                            "height": height,
                            "bg_img": img_url
                            }
                            %}


                </figure>

            </article>
    {% else %}
           <div class="info">Brak postow.</div>
    {% endfor %}

src/Aldor/InftechBundle/Resources/views/Block/recent_projects.html.twig
<h2 class="section-title ribbon ribbon-focus"><a href="{{ path('portfolio_home') }}"> {{ title}}</a></h2>

<div class="row entries">
    {% for entry in entities %}
    <article class="entry style-grid type-post col-md-6 col-lg-3 colheight-sm-1">
        
        <header class="entry-header">
            <p class="small">
            {% for tech in entry.technologies %}
            <a href="{{ path('portfolio_technology', {'slug': tech.slug })}}">{{ tech.name  }}</a>
            {% endfor %}
            
            </p>
            <h3 class="entry-title"><a href="{{ path('portfolio_project', {'slug': entry.slug }) }}">{{ entry.name}}</a> </h3>
          
            <div class="entry-meta">
            <h4><a href="{{ path('portfolio_project', {'slug': entry.slug }) }}"> {{entry.rawdescription|slice(0, 58)}} {% if entry.rawdescription|length > 58 %}...{% endif %} </a>
            </h4>
                <span class="entry-date"><a href="{{ path('portfolio_project', {'slug': entry.slug }) }}"><time datetime="{{entry.date|date(dateFormat)}}">{{ entry.date | time_ago_in_words(false, true) | trans }}</time></a></span>
            </div>
        </header>
        
        <figure class="entry-thumbnail">

            <a href="{{  path('portfolio_project', {'slug': entry.slug }) }}" class="overlay overlay-primary"></a>

            {% set img_url = media_public_url(entry.media, imageSize)   %}
            {% include "AldorInftechBundle::image.html.twig" with {
                "img_url": img_url,
                "alt": entry.name,
                "width": "480",
                "height": "280"
            }
            %}

        </figure>

    </article>
    {% endfor %}

</div><!--/.row.entries-->

src/Aldor/InftechBundle/Resources/views/Block/tags.html.twig
{% embed 'AldorInftechBundle::sidebar.html.twig'  %}
    {% block siedebar_title%}Tagi{% endblock%}
    {%block siedebar_content %}
    <div class="tagcloud">
    {% for tag in tags%}
    <a class="blog-tag" style="font-size:  {{ 2 *  tag.count }} em" href="{{ path('blog_tag', {'slug': tag.name }) }}">
        {{ tag.name}}
        </a>
    {%endfor%}

        </div>
    {% endblock%}
{% endembed %}