src/Aldor/PortfolioBundle/Entity/Project.php
<?php

namespace Aldor\PortfolioBundle\Entity;

use Aldor\InftechBundle\Utils\Inftech as Inftech;
use Doctrine\ORM\Mapping as ORM;
use Aldor\InftechBundle\Entity\Entry;

use Eko\FeedBundle\Item\Writer\ItemInterface;

/**
 * Aldor\PortfolioBundle\Entity\Project
 */
class Project extends Entry  implements ItemInterface
{
    /**
     * @var integer $id
     */
    protected $id;

    /**
     * @var string $name
     */
    protected $name;

    /**
     * @var string $description
     */
    protected $description;

    /**
     * @var string $url

     */
    protected $url;


    /**
     * @var Aldor\PortfolioBundle\Entity\Technology
     */
    protected $technology;


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Project
     */
    public function setName($name)
    {
        $this->name = $name;
        $this->slug = Inftech::slugify($name);

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }



    /**
     * Get name
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->name;
    }

    public function getTags()
    {
        return $this->technologies;
    }


    public function getCategory() {

        return 'Portfolio';
    }

    /**
     * Set description
     *
     * @param string $description
     * @return Project
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    public function getShortDescription()
    {
        $ile = 100;
        $licz = strlen($this->description);
        if ($licz>=$ile)  {
            $tnij = substr($this->description,0,$ile);
            $txt = $tnij."...";
        }
        else  {
            $txt = $tresc;
        }
        return $txt;
    }



    /**
     * Set url
     *
     * @param string $url
     * @return Project
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }


    /**
     * Set technology
     *
     * @param Aldor\PortfolioBundle\Entity\Technology $technology
     * @return Project
     */
    public function setTechnology(\Aldor\PortfolioBundle\Entity\Technology $technology = null)
    {
        $this->technology = $technology;

        return $this;
    }

    /**
     * Get technology
     *
     * @return Aldor\PortfolioBundle\Entity\Technology
     */
    public function getTechnology()
    {
        return $this->technology;
    }

     // ...

 public function getTechnologySlug()
 {
 return $this->getTechnology->getSlug();
 }
 public function getNameSlug()
 {
 return Portfolio::slugify($this->getName());
 }
    /**
     * @var \DateTime
     */
    protected $date;


    /**
     * Set date
     *
     * @param \DateTime $date
     * @return Project
     */
    public function setDate($date)
    {
        $this->date = $date;

        return $this;
    }

    /**
     * Get date
     *
     * @return \DateTime
     */
    public function getDate()
    {
        return $this->date;
    }
    /**
     * @var string
     */
    protected $slug;


    /**
     * Set slug
     *
     * @param string $slug
     * @return Project
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * Get slug
     *
     * @return \sring
     */
    public function getSlug()
    {
        return $this->slug;
    }
    /**
     * @ORM\PrePersist
     */
    public function prePersist()
    {
        // Add your code here
         $this->slug = Inftech::slugify($this->getName());
         $this->date = new \DateTime();
         $this->modified = $this->date;
         $this->url = $this->getName();
    }

    /**
     * @ORM\PreUpdate
     */
    public function preUpdate()
    {
        // Add your code here
         $this->slug = Inftech::slugify($this->getName());
         $this->modified = new \DateTime();
    }
    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    protected $technologies;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->technologies = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add technologies
     *
     * @param \Aldor\PortfolioBundle\Entity\Technology $technologies
     * @return Project
     */
    public function addTechnology(\Aldor\PortfolioBundle\Entity\Technology $technologies)
    {
        $this->technologies[] = $technologies;

        return $this;
    }

    /**
     * Remove technologies
     *
     * @param \Aldor\PortfolioBundle\Entity\Technology $technologies
     */
    public function removeTechnology(\Aldor\PortfolioBundle\Entity\Technology $technologies)
    {
        $this->technologies->removeElement($technologies);
    }

    /**
     * Get technologies
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getTechnologies()
    {
        return $this->technologies;
    }
    /**
     * @var string
     */
    protected $text;


    /**
     * Set text
     *
     * @param string $text
     * @return Project
     */
    public function setText($text)
    {
        $this->text = $text;

        return $this;
    }

    /**
     * Get text
     *
     * @return string
     */
    public function getText()
    {
        return $this->text;
    }

    public function __toString() {
        return $this->getName();
    }
    /**
     * @var string
     */
    protected $contentFormatter = 'richhtml';

    /**
     * @var string
     */
    protected $content;

    /**
     * @var string
     */
    protected $rawContent;

    /**
     * @var \Application\Sonata\MediaBundle\Entity\Media
     */
    protected $media;


    /**
     * Set contentFormatter
     *
     * @param string $contentFormatter
     * @return Project
     */
    public function setContentFormatter($contentFormatter)
    {
        $this->contentFormatter = $contentFormatter;

        return $this;
    }

    /**
     * Get contentFormatter
     *
     * @return string
     */
    public function getContentFormatter()
    {
        return $this->contentFormatter;
    }

    /**
     * Set content
     *
     * @param string $content
     * @return Project
     */
    public function setContent($content)
    {
        $this->content = $content;

        return $this;
    }

    /**
     * Get content
     *
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Set rawContent
     *
     * @param string $rawContent
     * @return Project
     */
    public function setRawContent($rawContent)
    {
        $this->rawContent = $rawContent;

        return $this;
    }

    /**
     * Get rawContent
     *
     * @return string
     */
    public function getRawContent()
    {
        return $this->rawContent;
    }

    /**
     * Set media
     *
     * @param \Application\Sonata\MediaBundle\Entity\Media $media
     * @return Project
     */
    public function setMedia(\Application\Sonata\MediaBundle\Entity\Media $media = null)
    {
        $this->media = $media;

        return $this;
    }

    /**
     * Get media
     *
     * @return \Application\Sonata\MediaBundle\Entity\Media
     */
    public function getMedia()
    {
        return $this->media;
    }

    public function getFeedItemTitle() {

        return $this->getName();

    }

    public function getFeedItemDescription() {

        return $this->getDescription();
    }
    public function getFeedItemPubDate() {
        return $this->getDate();

    }

    public function getFeedItemLink() {
        return $this->getSlug();
    }


    /**
     * @var string
     */
    protected $keywords;


    /**
     * Set keywords
     *
     * @param string $keywords
     * @return Project
    */
    public function setKeywords($keywords)
    {
        $this->keywords = $keywords;

        return $this;
    }

    /**
     * Get keywords
     *
     * @return string
     */
    public function getKeywords()
    {
        return $this->keywords;
    }
    /**
     * @var \DateTime
     */
    protected $modified;


    /**
     * Set modified
     *
     * @param \DateTime $modified
     * @return Project
     */
    public function setModified($modified)
    {
        $this->modified = $modified;

        return $this;
    }

    /**
     * Get modified
     *
     * @return \DateTime
     */
    public function getModified()
    {
        return $this->modified;
    }
    /**
     * @var boolean
     */
    protected $enabled_photo = true;


    /**
     * Set enabled_photo
     *
     * @param boolean $enabledPhoto
     * @return Project
     */
    public function setEnabledPhoto($enabledPhoto)
    {
        $this->enabled_photo = $enabledPhoto;

        return $this;
    }

    /**
     * Get enabled_photo
     *
     * @return boolean
     */
    public function getEnabledPhoto()
    {
        return $this->enabled_photo;
    }
    /**
     * @var string
     */
    protected $full_photo_size = 'big';


    /**
     * Set full_photo_size
     *
     * @param string $fullPhotoSize
     * @return Project
     */
    public function setFullPhotoSize($fullPhotoSize)
    {
        $this->full_photo_size = $fullPhotoSize;

        return $this;
    }

    /**
     * Get full_photo_size
     *
     * @return string
     */
    public function getFullPhotoSize()
    {
        return $this->full_photo_size;
    }

src/Aldor/PortfolioBundle/Controller/ProjectController.php
<?php

namespace Aldor\PortfolioBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;
use JMS\Serializer\SerializationContext;


use Aldor\InftechBundle\Cache\CacheManager;
use Aldor\InftechBundle\Controller\BaseController as BaseController;

use Aldor\PortfolioBundle\Entity\Project;
use Aldor\PortfolioBundle\Form\ProjectType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Cache;

/**
 * Project controller.
 *
 */
class ProjectController extends BaseController
{


    public function indexAction($page=1) {

        $this->construct();
        $res = new Response();
        $etag = 'cas';
        $cacheKey = CacheManager::KEY_PROJECT_ALL;
        $projects = $this->m_cacheManager->get($cacheKey, 'ArrayCollection<Aldor\PortfolioBundle\Entity\Project>');

        if(!$projects) {
            $projects = $this->m_em->getRepository('AldorPortfolioBundle:Project')->getAllProjects();
            $this->m_cacheManager->put($cacheKey, $projects, 6000, 'list');
        }

        $title = 'Projekty';
        $this->_setSeoData($title, 'Lista wykonanych projektów. Technologie nodejs, web, c, python');

        if (count($projects)) {
            $etag = md5("project:$page:{$projects[0]->getId()}:{$projects[0]->getModified()->format('Y-m-d H:i:s')}");
            $res = $this->_prepareResponse($etag, $projects[0]->getModified(), "+1080 seconds", 1080);
            if ($this->_isNotModified($res)) {
                return $res;
            }
        }

        $projects = $this->m_paginator->paginate($projects, $this->get('request')->query->get('strona', $page), $this->container->getParameter('max_post_on_page'));
        $projects->setUsedRoute('portfolio_home');
       

        return $this->render('AldorPortfolioBundle:Project:index.html.twig', array(
            'projects'      => $projects,
        ), $res);
    }


    public function showAction($slug)
    {
        $this->construct();

        $res = new Response();
        $pro = $this->m_em->getRepository('AldorPortfolioBundle:Project')->getOne($slug);

        if (!$pro) {
            throw $this->createNotFoundException('Unable to find Project entity.');
        }
        
        $title = $pro->getName().' | Projekty';
        $request = $this->container->get('request');
        $canonical = $this->get('router')->generate($request->attributes->get('_route'), array('slug' => $slug), true);
        $this->_setSeoData($title, $pro->getDescription(), $pro->getKeywords(), $canonical, $pro);

        $etag = md5("project:$slug:{$pro->getModified()->format('Y-m-d H:i:s')}");
        $res = $this->_prepareResponse($etag, $pro->getModified(), "+1080 seconds", 1080);
        if ($this->_isNotModified($res)) {
            return $res;
        }
      

        return $this->render('AldorPortfolioBundle:Project:show.html.twig', array(
            'project'      => $pro,
            'post' => $pro
       ), $res);
    }

    public function feedAction() {
        $this->construct();
        $res = new Response();
        $etag = 'cas';
        $cacheKey = CacheManager::KEY_PROJECT_ALL;
        $projects = $this->m_cacheManager->get($cacheKey, 'ArrayCollection<Aldor\PortfolioBundle\Entity\Project>');
        if(!$projects) {
            $projects = $this->m_em->getRepository('AldorPortfolioBundle:Project')->getAllProjects();
            $this->m_cacheManager->put($cacheKey, $projects, 6000, 'list');
        }
        $countProjects = count($projects);
        if (countProjects) {
            $etag = md5("project:$countProjects");
            $res = $this->_prepareResponse($etag, $projects[0]->getModified(), "+10800 seconds", 1080);
            if ($this->_isNotModified($res)) {
                $res->headers->set('Content-Type', 'application/rss+xml');
                return $res;
            }
        }
        $feed = $this->get('eko_feed.feed.manager')->get('projects');
        $feed->addFromArray($projects);
        $res->setContent($feed->render('atom'));
        $res->setCharset('UTF-8');
        $res->headers->set('Content-Type', 'application/xml');
        return $res;
    }
}

src/Aldor/PortfolioBundle/Resources/views/Project/index.html.twig
{% extends "AldorBlogBundle:Blog:index.html.twig" %}
{% block content %}
            <div id="content" class="content section row">

                <div class="col-md-8 bg-base col-lg-8 col-xl-9">

                    <div class="ribbon ribbon-highlight">
                        <ol class="breadcrumb ribbon-inner">
                            <li><a href="{{ path('page_slug', {'path': '/'}) }}" >Home</a></li>
                            <li><a href="{{ path('portfolio_home') }}" >Projekty</a></li>
                            {% if technology is defined %}
                                <li class="active">{{ technology.name }}</li>
                            {% endif %}

                        </ol>
                    </div>

                    <header class="page-header">
                        
                        <h2 class="page-title">
                            {% block portfolio_header %}
                                {% if technology  is defined %}
                                    {{ technology.name}}
                                {% else %}
                                    Projekty
                                {% endif %}
                            {% endblock portfolio_header %}
                        </h2>

                    </header>

                    <div class="entries">

                    {% for project in projects %}
                        <article class="entry style-media media type-post">


                            <figure class="media-object pull-left entry-thumbnail hidden-xs">

                                <a href="{{ path('portfolio_project', {'slug': project.slug}) }}" class="more-link">
                                  
                                        {% set img_url = media_public_url(project.media, 'small')   %}
                                {% include "AldorInftechBundle::image.html.twig" with {
                                    "img_url": img_url,
                                    "alt": project.name,
                                    "width": "230",
                                    "height": "230",
                                }
                                %} 
                                 </a>
                            
                            </figure>

                            <div class="media-body">
                                <header class="entry-header">
                                    <h3 class="entry-title">
                                    <a href="{{ path('portfolio_project', {'slug': project.slug}) }}" class="more-link">
                                        {{ project.name}}</a>
                                    </h3>

                                    <div class="entry-meta">
                                        <span class="author">Aldor</span>
                                        <span class="entry-date"> <time datetime="{{ project.date | date(dateFormat) }} ">{{ project.date | format_date(null, 'pl', 'Europe/Warsaw')}}</time></span>
                                        <span class="category"> 
                                            {% for tech in project.technologies %}
                                                <a href="{{ path('portfolio_technology', { 'slug': tech.slug}) }}"> {{ tech.name}} </a>
                                            {% endfor %}
                                        </span>
                                    </div>

                                </header>

                                    {{ project.description | raw}}
                                    <a href="{{path('portfolio_project', {'slug': project.slug}) }}" class="more-link">Czytaj więcej<i class="icon icon-long-arrow-right"></i></a>
                                </div>


                        </article>
                        {% else%}
                            Brak projektów.
                        {% endfor %}
                    </div>
        {{ knp_pagination_render(projects) }}
                </div>

{% endblock %}
{% block sidebar %}
                <div class="sidebar col-md-4 col-lg-4 col-xl-3">
     
                        {% if page is defined %}
                            {{ sonata_page_render_container('sidebar_right_1', page) }}
                        {% endif %}
                
                    {{ sonata_block_render({ 'type': 'aldor.block.service.tags' }, {
                        'title': 'Technologie',
                         'template': 'AldorPortfolioBundle:Technology:list.html.twig',
                         'routeName': 'portfolio_technology',
                          'entity': 'AldorPortfolioBundle:Technology',
                                'ribbon': 'ribbon-focus'

                    }) }}

        </div><!--/.sidebar col-md-4 col-lg-4 col-xl-3-->
    </div>

{% endblock %}

src/Aldor/PortfolioBundle/Resources/views/Project/show.html.twig
{% extends "AldorBlogBundle:Blog:post.html.twig" %}
{% block content %}

                    <div class="ribbon ribbon-highlight">
                        <ol class="breadcrumb ribbon-inner">
                            <li><a href="{{ path('page_slug', {'path': '/'}) }}" >Home</a></li>
                            <li><a href="{{ path('portfolio_home')}}">Projekty</a></li>
                            <li class="active" title="{{project.name}}">{{  project.name}}.</li>
                        </ol>
                    </div>
                    <div class="row">
                    <header class="page-header col-md-10 col-md-offset-1">
                        

                        <h2 class="page-title full-page-title">
                            {{ project.name}}
                        </h2>

                    </header>

                    <article class="entry style-single style-single-full type-project col-md-10 col-md-offset-1">
                        
                        {% if project.fullPhotoSize != 'none' %}
                        <figure class="entry-thumbnail">

                                {% set img_url = media_relative_url(project.media, project.fullPhotoSize)  %}
                                {% media project.media, project.fullPhotoSize with {'data-src':img_url , 'data-src-retina': img_url}%}
                            <noscript>
                                <img src="{% path project.media, 'big'  %}" alt="{{project.name}}">
                            </noscript>

                        </figure>
                        {% endif %}
                        <div class="entry-meta">
                            <span class="author">przez Aldor </span>
                                        <span class="entry-date"> <time datetime="{{ project.date | date(dateFormat) }} ">{{ project.date | date | format_date(null, 'pl', 'Europe/Warsaw') }}</time></span>
                            <span class="category">
                                            {% for tech in project.technologies %}
                                                <a href="{{ path('portfolio_technology', { 'slug': tech.slug}) }}"> {{ tech.name}} </a>
                                            {% endfor %}
                            </span>
                        </div>

                        <div class="entry-content">

                            <p class="lead">
                                {{ project.description|raw }}
                            </p>
                            {{ project.content|raw }}

                        </div>
                    </article>
                    <div class="col-md-10 col-md-offset-1">

                    <div class="after-entry">


                        <hr>

                        <aside class="widget">
                            Share:
                            <a href="#" class="" onclick="window.open(
                                'https://www.facebook.com/sharer/sharer.php?u='+encodeURIComponent(location.href), 
                                'facebook-share-dialog', 
                                'width=626,height=436'); 
                                return false;"><span class="icon-stack"><i class="icon-sign-blank icon-stack-base"></i><i class="icon-facebook icon-light"></i></span></a>
                            <a href="#" class="" onclick="window.open(
                                'http://twitter.com/home?status='+encodeURIComponent(location.href), 
                                'facebook-share-dialog', 
                                'width=626,height=436'); 
                                return false;"><span class="icon-stack"><i class="icon-sign-blank icon-stack-base"></i><i class="icon-twitter icon-light"></i></span></a>
                            <a href="#" class="" onclick="window.open(
                                'https://plus.google.com/share?url='+encodeURIComponent(location.href), 
                                'facebook-share-dialog', 
                                'width=500,height=436'); 
                                return false;"><span class="icon-stack"><i class="icon-sign-blank icon-stack-base"></i><i class="icon-google-plus icon-light"></i></span></a>
                            <a href="#" class="" onclick="javascript:void((function(){var e=document.createElement('script');e.setAttribute('type','text/javascript');e.setAttribute('charset','UTF-8');e.setAttribute('src','http://assets.pinterest.com/js/pinmarklet.js?r='+Math.random()*99999999);document.body.appendChild(e)})());"><span class="icon-stack"><i class="icon-sign-blank icon-stack-base"></i><i class="icon-pinterest icon-light"></i></span></a>
                        </aside> 

                    </div>
                    
                        </div>
                </div><!--/.col-md-8.col-lg-8.col-xl-9-->
{% endblock content %}